# Generated by Django 3.2.16 on 2022-10-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221015_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
