# Generated by Django 2.2.16 on 2022-10-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221018_1752'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique favorite',
        ),
    ]
